### ISSUE TITLE
setup.sh does not download dependencies

### ISSUE THREAD

**Issue by notKamui** [TheRealKizu/dotfiles#1]
Tested in TTY:

As the name of the issue suggests, the script doesn't properly downloads the dependencies and terminates before doing so.

It should check beforehand if the user has already an AUR helper installed (yay, or paru, among others) and the try to install one if not.

**Comment by TheRealKizu** [comment]
Seems to be working now.

**Comment by notKamui** [comment]
indeed, seems good to me now.

nitpicking, but a check for `paru` before the one for `yay` would be good too i think (since more and more people are transitioning from yay to paru). If neither paru nor yay is installed, you can let yay be installed like you did.

**Comment by TheRealKizu** [comment]
Added paru support in a29139b
