### ISSUE TITLE
wallpaper reverts to black after reboot or shutdown

### ISSUE THREAD

**Issue by Ichinose11** [TheRealKizu/dotfiles#10]
i used nitrogen to set the wallpaper but whenever i either reboot or shutdown the system the wallpaper turns black after the system boots up again

**Comment by TheRealKizu** [comment]
Have you set it an autostart command on [bspwmrc](https://github.com/TheRealKizu/dotfiles/blob/master/cfg/bspwm/bspwmrc)?

**Comment by Ichinose11** [comment]
no

**Comment by Ichinose11** [comment]
do i add nitrogen --restore to my bspwmrc?

**Comment by TheRealKizu** [comment]
> 
> 
> do i add nitrogen --restore to my bspwmrc?

Yes

**Comment by Ichinose11** [comment]
> Yes
how do i do this and where do i put it?

**Comment by TheRealKizu** [comment]
> 
> 
> > Yes
> 
> how do i do this and where do i put it?

Add the nitrogen command in a new line in bspwmrc?

**Comment by Ichinose11** [comment]
> Add the nitrogen command in a new line in bspwmrc?

didn't fixed it

**Comment by Ichinose11** [comment]
![image](https://user-images.githubusercontent.com/77606488/132990353-36e866de-5121-424c-af68-bef1f9808084.png)
like this right?

**Comment by TheRealKizu** [comment]
Yeah

**Comment by Ichinose11** [comment]
> Yeah

didn't fixed it

**Comment by Ichinose11** [comment]
![image](https://user-images.githubusercontent.com/77606488/133091440-b6b5e42a-4cf9-484e-beae-ce366faad846.png)
also i found the same command in .config bspwm.bak>bspwmrc script

**Comment by TheRealKizu** [comment]
> > Yeah
> 
> didn't fixed it

Have you try putting it before line 53?

**Comment by Ichinose11** [comment]
> Have you try putting it before line 53?

yes on line 52 ?? it didn't help

**Comment by Ichinose11** [comment]
its fixed 👍
