### ISSUE TITLE
error in nvim 

### ISSUE THREAD

**Issue by Ichinose11** [TheRealKizu/dotfiles#11]
![image](https://user-images.githubusercontent.com/77606488/133118889-3973a00b-009d-4cf9-aa70-3dc811ede422.png)
what's this error does this matter or should i ignore this ? running nvim 0.5.0

**Comment by TheRealKizu** [comment]
The nvim config is a separate repo from this. You can check it [here](https://github.com/TheRealKizu/neodots)

**Comment by Ichinose11** [comment]
does your dotfiles also copies the nvim config in that repo ? so now i need to install packer ?

**Comment by TheRealKizu** [comment]
> does your dotfiles also copies the nvim config in that repo ? so now i need to install packer ?

I'm sure it does if you clone the submodules too. Yes, you need to install packer.nvim.

**Comment by Ichinose11** [comment]
> > does your dotfiles also copies the nvim config in that repo ? so now i need to install packer ?
> 
> I'm sure it does if you clone the submodules too. Yes, you need to install packer.nvim 
installed packer and i copied your submodules earlier but :PackerSync command doesn't run giving me an error "not an editor command"

**Comment by TheRealKizu** [comment]
> 
> 
> > > does your dotfiles also copies the nvim config in that repo ? so now i need to install packer ?
> > 
> > 
> > I'm sure it does if you clone the submodules too. Yes, you need to install packer.nvim
> 
> installed packer and i copied your submodules earlier but :PackerSync command doesn't run giving me an error "not an editor command"

Is your neovim version >= 0.5.0?

**Comment by Ichinose11** [comment]
> > > > does your dotfiles also copies the nvim config in that repo ? so now i need to install packer ?
> > > 
> > > 
> > > I'm sure it does if you clone the submodules too. Yes, you need to install packer.nvim
> > 
> > 
> > installed packer and i copied your submodules earlier but :PackerSync command doesn't run giving me an error "not an editor command"
> 
> Is your neovim version >= 0.5.0?

= 0.5.0

**Comment by Ichinose11** [comment]
> > > > does your dotfiles also copies the nvim config in that repo ? so now i need to install packer ?
> > > 
> > > 
> > > I'm sure it does if you clone the submodules too. Yes, you need to install packer.nvim
> > 
> > 
> > installed packer and i copied your submodules earlier but :PackerSync command doesn't run giving me an error "not an editor command"
> 
> Is your neovim version >= 0.5.0?

its an issue with your nvim config i deleted your nvim config the editor came up with no errors
