### ISSUE TITLE
not able to make alacritty transparent 

### ISSUE THREAD

**Issue by Ichinose11** [TheRealKizu/dotfiles#12]
i used the following code to make the terminal transparent but it didn't worked 
# Background opacity
#
# Window opacity as a floating point number from `0.0` to `1.0`.
# The value `0.0` is completely transparent and `1.0` is opaque.
background_opacity: 0.9

**Comment by TheRealKizu** [comment]
"Opacity is the inverse of transparency. So to get a completely transparent window, you'll have to set the opacity to 0.0 instead of 1.0."

**Comment by Ichinose11** [comment]
> "Opacity is the inverse of transparency. So to get a completely transparent window, you'll have to set the opacity to 0.0 instead of 1.0."

i literally have tried to put all possible values but the terminal won't go transparent, your alacritty config didn't have that code i tried to put it in that config but it didn't helped do i need to edit the picom config too ? also can you push this(feature request)

**Comment by TheRealKizu** [comment]
Yeah, try setting the transparency on picom too

**Comment by Ichinose11** [comment]
> Yeah, try setting the transparency on picom too

should i do something in `opacity-rule = [ ]` ?
