### ISSUE TITLE
GetUsedRam doesn't work.

### ISSUE THREAD

**Issue by SmellsNice** [TheRealKizu/dotfiles#13]
"sh ~/.config/eww/scripts/getUsedRam" always returns something along the lines of printf: 20:1476: invalid number and as such doesn't actually work.

**Comment by TheRealKizu** [comment]
Can you try running `printf "%.0f\n" $(free -m | grep Mem | awk '{print ($3/$2)*100}')` on a terminal?

**Comment by SmellsNice** [comment]
That seems to work without any errors.

**Comment by SmellsNice** [comment]
Anyways I've "solved" the issue by removing the ram module and editing the eww config accordingly, will close issue for now.
