### ISSUE TITLE
System tray

### ISSUE THREAD

**Issue by ThatOneOcto** [TheRealKizu/dotfiles#17]
How do I enable the system tray, I tried enabling it in the ~/.config/polybar/config.ini and it didn't work
I added tray-position = right fyi

**Comment by TheRealKizu** [comment]
Enable it [here](https://github.com/TheRealKizu/dotfiles/blob/59f837dbdb3e6e0527b460d89f14d861b8a340e0/cfg/polybar/bars.ini#L126)

**Comment by ThatOneOcto** [comment]
### Thanks it worked
