### ISSUE TITLE
feat: add 1920x1080p version of eww widget

### ISSUE THREAD

**Issue by TheRealKizu** [TheRealKizu/dotfiles#4]
as the title says

**Comment by TheRealKizu** [comment]
damn I'm broke to buy a new monitor

**Comment by flyingcakes85** [comment]
I've added the config here : https://github.com/flyingcakes85/dotfiles/blob/eww-1080/cfg/eww/eww-1080.xml

Gonna do a pull request if you find it ok

**Comment by TheRealKizu** [comment]
> I've added the config here : [https://github.com/flyingcakes85/dotfiles/blob/eww-1080/cfg/eww/eww-1080.xml](https://github.com/flyingcakes85/dotfiles/blob/eww-1080/cfg/eww/eww-1080.xml?rgh-link-date=2021-07-28T01%3A38%3A38Z)
> 
> Gonna do a pull request if you find it ok

Please do it :>

**Comment by PR454D** [comment]
I suppose you have a 1366x768 monitor @TheRealKizu? I'm sure you can do it on your own. hint: Xorg-xrandr?

**Comment by TheRealKizu** [comment]
Fixed in #5

**Comment by TheRealKizu** [comment]
> I suppose you have a 1366x768 monitor @TheRealKizu? I'm sure you can do it on your own. hint: Xorg-xrandr?

I can but xrandr just says that the resolution is not found in available modes

**Comment by flyingcakes85** [comment]
You could use Xorg-Xephyr to create a virtual display of whichever resolution you want.
https://wiki.archlinux.org/title/Xephyr

For 1080p,

    Xephyr -br -ac -noreset -screen 1920x1080 :1

You will get a black screen. Use mod+mouse drag to move the window to a side. Then in another terminal, run

    DISPLAY=:1 bspwm

Messy solution, but always works, and not so bad when you don't need to look at the whole screen at once.

**Comment by TheRealKizu** [comment]
> You could use Xorg-Xephyr to create a virtual display of whichever resolution you want.
> [wiki.archlinux.org/title/Xephyr](https://wiki.archlinux.org/title/Xephyr)
> 
> For 1080p,
> 
> ```
> Xephyr -br -ac -noreset -screen 1920x1080 :1
> ```
> 
> You will get a black screen. Use mod+mouse drag to move the window to a side. Then in another terminal, run
> 
> ```
> DISPLAY=:1 bspwm
> ```
> 
> Messy solution, but always works, and not so bad when you don't need to look at the whole screen at once.

Thanks! :D
